apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ include "chart.metadataName.clusterIssuer.backend" . }}
spec:
  acme:
    server: {{ .Values.issuer.server }}
    email: {{ .Values.issuer.email }}
    privateKeySecretRef:
      name: {{ .Values.issuer.backend.privateKeySecretRef }}
    solvers:
    {{- range .Values.issuer.backend.ingress }}
    - http01:
        ingress:
          class: {{ .class }}
          podTemplate:
            spec:
              nodeSelector:
                {{- toYaml .nodeSelector | nindent 16 }}
    {{- end }}

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ include "chart.metadataName.clusterIssuer.frontend" . }}
spec:
  acme:
    server: {{ .Values.issuer.server }}
    email: {{ .Values.issuer.email }}
    privateKeySecretRef:
      name: {{ .Values.issuer.frontend.privateKeySecretRef }}
    solvers:
    {{- range .Values.issuer.frontend.ingress }}
    - http01:
        ingress:
          class: {{ .class }}
          podTemplate:
            spec:
              nodeSelector:
                {{- toYaml .nodeSelector | nindent 16 }}
    {{- end }}