apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.metadataName.backend" . }}
  namespace: {{ .Values.namespace.backend }}
spec:
  type: {{ .Values.service.type.backend }}
  ports:
    - port: {{ .Values.service.port }}
  selector:
    {{- include "chart.selectorLabels.backend" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.metadataName.frontend" . }}
  namespace: {{ .Values.namespace.frontend }}
spec:
  type: {{ .Values.service.type.frontend }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    {{- include "chart.selectorLabels.frontend" . | nindent 4 }}